### ISSUE TITLE
Keeping GitOps in mind

### ISSUE THREAD

**Issue by jaitaiwan** [PeerDB-io/peerdb-enterprise#5]
Hey folks, 

When installing helm charts using a gitops workflow, its preferable that most of the configuration and deployment happens with in-cluster operators or during the pipeline. The workflow that's documented here suggests to me that I can't create a helm chart and repository definition as well as inject values, I have to use the extra shell scripts to get the entire process working...

Do you have guides for folks making use of Flux or ArgoCD?

Thanks

**Comment by iamKunalGupta** [comment]
https://github.com/PeerDB-io/peerdb-enterprise/blob/main/PRODUCTION.md
This guide should help you out. Additionally, to simply test you can add the argument `template` like so in the shell scripts to render the templates and generate the secret based yamls:
```shell
./install_catalog.sh template > rendered_catalog.yaml
```
OR
```shell
./install_peerdb.sh template > rendered_peerdb.yaml
```

**Comment by iamKunalGupta** [comment]
Additionally, we have a helm charts repository internally with packaged helm charts, but we plan to add the packaged helm charts here as well. https://github.com/PeerDB-io/peerdb-enterprise/issues/6

**Comment by jaitaiwan** [comment]
Awesome thanks for the info.
