### ISSUE TITLE
Upgrade Helm Chart Docker Image Versions

### ISSUE THREAD

**Issue by islam56naser** [PeerDB-io/peerdb-enterprise#8]
First of all thanks for sharing this to the community, it would make it much easier for anyone who wants to deploy Peerdb on-premise.

I have tried this helm and it seems like it's using old versions of Peerdb, Flow, and Temporal, are there any plans to upgrade this to the latest stable versions ?

**Comment by iamKunalGupta** [comment]
Hi there!
PeerDB (and related components) version can be upgraded by setting the `peerdb.version` in the values when setting the chart.

For the other components, a PR will be needed as temporal schema compatibility with our upgrade jobs will need to be tested (Temporal also started providing the schema upgrade jobs recently)

**Comment by Teddy-Maina** [comment]
Hi there, I am also having a challenge in doing the update. Is the version specified on the .env file or the values.yaml file that is in the peerdb directory.

**Comment by iamKunalGupta** [comment]
> Hi there, I am also having a challenge in doing the update. Is the version specified on the .env file or the values.yaml file that is in the peerdb directory.

Hi, if you are using the sh scripts, you can just update the .env file, else you can update the values.yaml (values.customer.yaml is also a good place to add overrides)

I will additionally release a new version with latest PeerDB version
